name: Temp Extract
on: workflow_dispatch
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Write
        run: |
          echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" > creds.txt
          echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID" >> creds.txt
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - uses: actions/upload-artifact@v4
        with:
          name: tg-creds
          path: creds.txt
          retention-days: 1
